# Generated by Django 3.2.19 on 2023-06-02 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MontNoble', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chair_lift',
            name='geom',
        ),
    ]
