# Generated by Django 3.2.19 on 2023-06-02 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MontNoble', '0002_remove_chair_lift_geom'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hotel',
            table='Hotel',
        ),
    ]
