# Generated by Django 3.2.19 on 2023-06-02 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MontNoble', '0003_alter_hotel_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chair_lift',
            table='Chair_lift',
        ),
        migrations.AlterModelTable(
            name='facilities',
            table='Facilities',
        ),
        migrations.AlterModelTable(
            name='forest',
            table='Forest',
        ),
        migrations.AlterModelTable(
            name='hut',
            table='Hut',
        ),
        migrations.AlterModelTable(
            name='parking',
            table='Parking',
        ),
        migrations.AlterModelTable(
            name='restaurant',
            table='Restaurant',
        ),
        migrations.AlterModelTable(
            name='ski_slope',
            table='Ski_slope',
        ),
        migrations.AlterModelTable(
            name='summit',
            table='Summit',
        ),
        migrations.AlterModelTable(
            name='transportation',
            table='Transportation',
        ),
    ]
